name: Deploy to AWS ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Log in to Amazon ECR
        id: ecr-login
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin <YOUR_ECR_REGISTRY_URL>

      - name: Build Docker image
        run: |
          docker build -t <YOUR_ECR_REGISTRY_URL>/<YOUR_REPOSITORY_NAME>:latest .

      - name: Push Docker image to Amazon ECR
        run: |
          docker push <YOUR_ECR_REGISTRY_URL>/<YOUR_REPOSITORY_NAME>:latest

      - name: Deploy to ECS
        run: |
          aws ecs update-service --cluster <YOUR_ECS_CLUSTER_NAME> --service <YOUR_ECS_SERVICE_NAME> --force-new-deployment
